# -*- coding: utf-8 -*-
"""quiz3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c5DpoIknQN7OZaBzp2pGiIWHMRMwfi0k

Load data into pandas, clean it (remove nulls), and plot a bar graph of article categories.
"""

import pandas as pd

df = pd.read_csv("/content/archive.csv")

df.rename(columns={
    'February Average Temperature': 'February',
    'February Average Temperature (Northeast)': 'February_NE',
    'February Average Temperature (Midwest)': 'February_MW',
    'February Average Temperature (Pennsylvania)': 'February_PA',
    'March Average Temperature': 'March',
    'March Average Temperature (Northeast)': 'March_NE',
    'March Average Temperature (Midwest)': 'March_MW',
    'March Average Temperature (Pennsylvania)': 'March_PA'
}, inplace=True)

df_clean = df.dropna()

# Take mean of all temperature columns
avg_temps = df_clean.mean(numeric_only=True)

# Plot bar graph
plt.figure(figsize=(12,6))
avg_temps.plot(kind='bar')
plt.title("Average Temperatures by Month and Region")
plt.xlabel("Month / Region")
plt.ylabel("Temperature (°F)")
plt.xticks(rotation=45, ha='right')
plt.show()